### ISSUE TITLE
Switch to Inkey Wallet

### ISSUE THREAD

**Issue by youraerials** [thencc/Irulan#29]

**Comment by enceladus** [comment]
Was working on this today, ran into a weird bug. Maybe you have some insight on this @spencercap ?

Basically, calling `algonaut.inkeyConnect()` gives me this error immediately:

```
FrameBus.ts:1720 DOMException: Blocked a frame with origin "http://localhost:4000" from accessing a cross-origin frame.
    at isRef (http://localhost:4000/node_modules/.vite/deps/chunk-U2LQBB2R.js?v=29679eb3:1082:20)
    at Object.get2 [as get] (http://localhost:4000/node_modules/.vite/deps/chunk-U2LQBB2R.js?v=29679eb3:631:9)
    at Proxy.emitAsync (http://localhost:4000/@fs/Users/d/Documents/work/ncc/algonautjs/dist/index.mjs:537:98331)
    at Proxy.inkeyMessageAsync (http://localhost:4000/@fs/Users/d/Documents/work/ncc/algonautjs/dist/index.mjs:570:202249)
    at async Proxy.inkeyConnect (http://localhost:4000/@fs/Users/d/Documents/work/ncc/algonautjs/dist/index.mjs:570:202942)
```

Looks like the problem is in Vite calling `isRef` on the iframe, i.e. "trying to access it"?

This breaks `inkeyConnect()` — while the connection still happens, and the iframe sends a PostMessage back to the client with the account address, the client has already moved on, accepting this DOMException as the fulfillment of the `await` call, so:

```js
const account = await state.sAlgo.algonaut.inkeyConnect()
console.log(account)
```

`account` is null here.

Any ideas?

**Comment by enceladus** [comment]
And I don't _think_ this is an algonautjs bug, because it doesn't happen in other instances of using Inkey.

**Comment by enceladus** [comment]
Ahhhhhh, ok so I think the problem is that `algonaut` is wrapped in a Vue `reactive()`, so Vue is indeed trying to inspect all of her children.

Most people seem to be using `Object.freeze()` to block reactivity for an element, but this would also prevent us from initializing / changing anything about `FrameBus`.

**Comment by spencercap** [comment]
ahh whoa, yeah - this is a weird one. i'd also look into `markRaw` and the secret flag `__v_skip `.

check out the "Second: more reactivity APIs" section of this helpful vue reactivity tutorial:
https://dev.to/jinjiang/understanding-reactivity-in-vue-3-0-1jni

**Comment by spencercap** [comment]
a bit hackery but i reckon there might be a solution w something like:

```js
Object.defineProperty(
  state.sAlgo.algonaut, // theReactiveObj
  '__v_skip',
  { value: true }
);
```

**Comment by enceladus** [comment]
I feel like we still need `sAlgo.algonaut` to be reactive though? Aren't we using it to pull the current account and things like that?

**Comment by spencercap** [comment]
oh yes. how about this?

```js

Object.defineProperty(
  state.sAlgo.algonaut.inkeyWallet.frameBus.walWin, // theReactiveObj
  '__v_skip',
  { value: true }
);
```

i bet the cross reference comes from there since we keep a reference to that window to postmessage to IN the class which is in reactive state object.

**Comment by spencercap** [comment]
how can i test this? where's a good place to drop in w the problem reproducible?

**Comment by enceladus** [comment]
I updated y'all in the group chat, but to keep this repo canon, check out https://github.com/thencc/Irulan/commit/8ed35bb6840271de6b7a067da29bc3b4ddb3a45c

The main change being:

```js
this.algonaut = markRaw(new Algonaut(algoConfig));
```

Inkey appears to work, as far as I've tested things, but be on the look out for any algonaut-related bugs that might be caused by `markRaw`.
